# Generated by Django 6.0.7 on 2026-08-17 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentition_type', models.CharField(choices=[('adult', 'Adult (Permanent)'), ('primary', 'Primary (Milk teeth)')], default='adult', max_length=10)),
                ('tooth_number', models.CharField(max_length=5)),
                ('surface', models.CharField(choices=[('mesial', 'Mesial'), ('distal', 'Distal'), ('occlusal', 'Occlusal'), ('buccal', 'Buccal'), ('lingual', 'Lingual'), ('incisal', 'Incisal'), ('whole', 'Whole Tooth')], default='whole', max_length=10)),
                ('condition', models.CharField(choices=[('decay', 'Decay'), ('filling', 'Filling'), ('crown', 'Crown'), ('bridge', 'Bridge'), ('implant', 'Implant'), ('rct', 'Root Canal Treated'), ('missing', 'Missing'), ('impacted', 'Impacted'), ('unerupted', 'Unerupted'), ('supernumerary', 'Supernumerary'), ('fracture', 'Fracture'), ('mobility', 'Mobility'), ('sensitivity', 'Sensitivity'), ('healthy', 'Healthy')], max_length=20)),
                ('status', models.CharField(choices=[('existing', 'Existing'), ('planned', 'Planned'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='existing', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrthodonticDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(blank=True, max_length=100)),
                ('bracket_type', models.CharField(blank=True, max_length=100)),
                ('wire_size', models.CharField(blank=True, max_length=50)),
                ('position_notes', models.TextField(blank=True)),
                ('adjustment_date', models.DateField(blank=True, null=True)),
                ('tooth_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orthodontic_detail', to='dental_chart.toothrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ImplantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('placement_date', models.DateField(blank=True, null=True)),
                ('bone_graft_material', models.CharField(blank=True, max_length=150)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tooth_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implant_detail', to='dental_chart.toothrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EndodonticDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('canal_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obturation_date', models.DateField(blank=True, null=True)),
                ('technique_notes', models.TextField(blank=True)),
                ('tooth_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endodontic_detail', to='dental_chart.toothrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ToothRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tooth_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dental_chart.toothrecord')),
            ],
        ),
    ]
