# Generated by Django 6.0.7 on 2026-08-24 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General'), ('orthodontic', 'Orthodontic'), ('surgical', 'Surgical'), ('cosmetic', 'Cosmetic'), ('emergency', 'Emergency'), ('pediatric', 'Pediatric'), ('periodontal', 'Periodontal'), ('prosthodontic', 'Prosthodontic (crowns/dentures/implants)')], default='general', max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_summary', models.TextField(blank=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_opened', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CaseVisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('examination_findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('procedure_performed', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('next_appointment_notes', models.TextField(blank=True)),
                ('ai_generated_summary', models.TextField(blank=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_notes_as_assistant', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='case_files.case')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_notes_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=150)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('visit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='case_files.casevisitnote')),
            ],
        ),
    ]
