/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9fa",
        "secondary-fixed": "#d8e3fb",
        "surface-dim": "#d9dadb",
        "on-background": "#191c1d",
        "primary-container": "#008378",
        "on-secondary-container": "#586377",
        "surface-variant": "#e1e3e4",
        "tertiary-container": "#a36700",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "secondary": "#545f73",
        "on-secondary-fixed-variant": "#3c475a",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#bcc9c6",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-error": "#ffffff",
        "outline": "#6d7a77",
        "on-secondary-fixed": "#111c2d",
        "inverse-primary": "#6bd8cb",
        "surface": "#f8f9fa",
        "on-primary-fixed": "#00201d",
        "tertiary-fixed": "#ffddb8",
        "background": "#f8f9fa",
        "surface-tint": "#006a61",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "on-primary-container": "#f4fffc",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary": "#825100",
        "on-tertiary-fixed-variant": "#653e00",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#3d4947",
        "surface-container-highest": "#e1e3e4",
        "primary": "#00685f",
        "secondary-container": "#d5e0f8",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#005049",
        "surface-container": "#edeeef",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-padding": "2rem",
        "grid-gutter": "1rem",
        "container-gap": "1.5rem",
        "sidebar-width": "260px",
        "stack-space": "1rem"
      },
    },
  },
  plugins: [],
}
