-- =============================================================================
-- DATABASE SCHEMA DDL SCRIPT FOR DR. CHANDRIKA HOSPITAL MANAGEMENT SYSTEM
-- Target Engine: PostgreSQL 14+ (Standard SQL Compatible)
-- Project: Dr. Chandrika Hospital Management Tool
-- Description: Complete Database Schema including Users, Patients, Vitals,
--              Duplicate Detection, Dental Charting, and Audit Logs.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. SYSTEM & AUTHENTICATION TABLES (django_content_type, auth_permission, auth_group, accounts_user)
-- =============================================================================

-- Table: django_content_type
-- Registry of installed models for generic foreign keys and permission mapping
CREATE TABLE IF NOT EXISTS public.django_content_type (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_uniq UNIQUE (app_label, model)
);
COMMENT ON TABLE public.django_content_type IS 'Registry of framework content types and model references.';

-- Table: auth_permission
-- Granular system permissions linked to content types
CREATE TABLE IF NOT EXISTS public.auth_permission (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    content_type_id integer NOT NULL REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
    codename varchar(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_id_codename_uniq UNIQUE (content_type_id, codename)
);
COMMENT ON TABLE public.auth_permission IS 'System permissions mapping codenames to models.';

-- Table: auth_group
-- Role-based authorization groups
CREATE TABLE IF NOT EXISTS public.auth_group (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE
);
COMMENT ON TABLE public.auth_group IS 'User role/permission groups.';

-- Table: accounts_user
-- Custom User model representing hospital staff, doctors, accountants, and patients
CREATE TABLE IF NOT EXISTS public.accounts_user (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password varchar(128) NOT NULL,
    last_login timestamp with time zone NULL,
    is_superuser boolean NOT NULL DEFAULT FALSE,
    username varchar(150) NOT NULL UNIQUE,
    first_name varchar(150) NOT NULL,
    last_name varchar(150) NOT NULL,
    email varchar(254) NOT NULL,
    is_staff boolean NOT NULL DEFAULT FALSE,
    is_active boolean NOT NULL DEFAULT TRUE,
    date_joined timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role varchar(20) NOT NULL CHECK (role IN ('chief_doctor', 'doctor', 'assistant', 'receptionist', 'accountant', 'patient')),
    phone varchar(15) NULL UNIQUE,
    photo varchar(100) NULL,
    status varchar(10) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    mfa_enabled boolean NOT NULL DEFAULT FALSE,
    biometric_enabled boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE public.accounts_user IS 'Hospital central user registry with role-based access control (RBAC).';
COMMENT ON COLUMN public.accounts_user.role IS 'User role: chief_doctor, doctor, assistant, receptionist, accountant, patient';
COMMENT ON COLUMN public.accounts_user.mfa_enabled IS 'Multi-factor authentication status';
COMMENT ON COLUMN public.accounts_user.biometric_enabled IS 'Biometric login flag for supported devices';

-- User - Group mapping
CREATE TABLE IF NOT EXISTS public.accounts_user_groups (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
    group_id integer NOT NULL REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT accounts_user_groups_user_id_group_id_uniq UNIQUE (user_id, group_id)
);

-- User - Permission mapping
CREATE TABLE IF NOT EXISTS public.accounts_user_user_permissions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED,
    permission_id integer NOT NULL REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT accounts_user_user_permissions_user_id_permission_id_uniq UNIQUE (user_id, permission_id)
);

-- Group - Permission mapping
CREATE TABLE IF NOT EXISTS public.auth_group_permissions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
    permission_id integer NOT NULL REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_group_id_permission_id_uniq UNIQUE (group_id, permission_id)
);


-- =============================================================================
-- 2. ACCOUNTS SECURITY & AUDIT TABLES
-- =============================================================================

-- Table: accounts_loginhistory
-- Tracking login attempts and active sessions
CREATE TABLE IF NOT EXISTS public.accounts_loginhistory (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    ip_address inet NULL,
    device_info varchar(255) NULL,
    login_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    logout_at timestamp with time zone NULL,
    status varchar(20) NOT NULL DEFAULT 'success'
);
COMMENT ON TABLE public.accounts_loginhistory IS 'Audit log of user login sessions and IP/device metadata.';

-- Table: accounts_otpverification
-- One-Time Password tokens for 2FA and password resets
CREATE TABLE IF NOT EXISTS public.accounts_otpverification (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    otp_code varchar(6) NOT NULL,
    purpose varchar(50) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    verified boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE public.accounts_otpverification IS 'Stores OTP codes for 2FA, logins, and password resets.';

-- Table: accounts_auditlog
-- Enterprise audit logging of change operations
CREATE TABLE IF NOT EXISTS public.accounts_auditlog (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    action varchar(50) NOT NULL,
    module varchar(50) NOT NULL,
    record_id varchar(50) NULL,
    old_value jsonb NULL,
    new_value jsonb NULL,
    timestamp timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE public.accounts_auditlog IS 'Comprehensive system audit log tracking model modifications and actions.';


-- =============================================================================
-- 3. PATIENTS MANAGEMENT TABLES
-- =============================================================================

-- Table: patients_patient
-- Main patient demographics and status record
CREATE TABLE IF NOT EXISTS public.patients_patient (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code varchar(20) NOT NULL UNIQUE,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL DEFAULT '',
    dob date NULL,
    gender varchar(10) NOT NULL DEFAULT '' CHECK (gender IN ('', 'male', 'female', 'other')),
    phone varchar(15) NULL UNIQUE,
    email varchar(254) NULL,
    address text NOT NULL DEFAULT '',
    city varchar(100) NOT NULL DEFAULT '',
    state varchar(100) NOT NULL DEFAULT '',
    country varchar(100) NOT NULL DEFAULT 'India',
    preferred_language varchar(50) NOT NULL DEFAULT '',
    photo varchar(100) NULL,
    emergency_contact_name varchar(100) NOT NULL DEFAULT '',
    emergency_contact_phone varchar(15) NOT NULL DEFAULT '',
    referral_source varchar(100) NOT NULL DEFAULT '',
    abha_id varchar(50) NULL,
    status varchar(10) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'merged')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    linked_user_id bigint UNIQUE NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    registered_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    merged_into_id bigint NULL REFERENCES public.patients_patient(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.patients_patient IS 'Core patient demographic records, ABHA integration, and status tracking.';
COMMENT ON COLUMN public.patients_patient.patient_code IS 'Formatted unique patient code (e.g. PT00001)';
COMMENT ON COLUMN public.patients_patient.abha_id IS 'Ayushman Bharat Health Account (ABHA) ID';

-- Table: patients_guardian
-- Guardians or emergency representatives for pediatric or dependent patients
CREATE TABLE IF NOT EXISTS public.patients_guardian (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name varchar(100) NOT NULL,
    relationship varchar(50) NOT NULL,
    phone varchar(15) NOT NULL DEFAULT '',
    id_proof_type varchar(50) NOT NULL DEFAULT '',
    id_proof_number varchar(50) NOT NULL DEFAULT ''
);
COMMENT ON TABLE public.patients_guardian IS 'Patient guardian/family relationship and identity proof details.';

-- Table: patients_medicalhistory
-- Recorded existing medical conditions and systemic health alerts
CREATE TABLE IF NOT EXISTS public.patients_medicalhistory (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    condition_name varchar(150) NOT NULL,
    diagnosed_date date NULL,
    notes text NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.patients_medicalhistory IS 'Pre-existing and active medical conditions per patient.';

-- Table: patients_allergy
-- Patient drug, food, or material allergy tracking
CREATE TABLE IF NOT EXISTS public.patients_allergy (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    allergen varchar(150) NOT NULL,
    reaction varchar(255) NOT NULL DEFAULT '',
    severity varchar(10) NOT NULL DEFAULT 'mild' CHECK (severity IN ('mild', 'moderate', 'severe')),
    recorded_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.patients_allergy IS 'Known patient allergies with reaction notes and severity flags.';

-- Table: patients_familylink
-- Cross-links family members registered as separate patients
CREATE TABLE IF NOT EXISTS public.patients_familylink (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    related_patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    relationship varchar(50) NOT NULL
);
COMMENT ON TABLE public.patients_familylink IS 'Relational link mapping family members in the hospital system.';


-- =============================================================================
-- 4. VITALS MONITORING TABLES
-- =============================================================================

-- Table: vitals_vitals
-- Clinical vitals recorded during registration, pre-op, procedure, or post-op
CREATE TABLE IF NOT EXISTS public.vitals_vitals (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    context varchar(20) NOT NULL CHECK (context IN ('registration', 'pre_treatment', 'intra_procedure', 'post_treatment')),
    bp_systolic integer NULL CHECK (bp_systolic >= 0),
    bp_diastolic integer NULL CHECK (bp_diastolic >= 0),
    pulse integer NULL CHECK (pulse >= 0),
    blood_sugar integer NULL CHECK (blood_sugar >= 0),
    temperature numeric(4, 1) NULL,
    spo2 integer NULL CHECK (spo2 >= 0 AND spo2 <= 100),
    weight_kg numeric(5, 2) NULL,
    height_cm numeric(5, 2) NULL,
    notes text NOT NULL DEFAULT '',
    is_flagged boolean NOT NULL DEFAULT FALSE,
    flagged_reason varchar(255) NOT NULL DEFAULT '',
    recorded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.vitals_vitals IS 'Patient vitals logs with automated clinical risk threshold flagging.';
COMMENT ON COLUMN public.vitals_vitals.is_flagged IS 'True if BP, pulse, sugar, or SpO2 exceeds safe limits';
COMMENT ON COLUMN public.vitals_vitals.temperature IS 'Body temperature in Fahrenheit';


-- =============================================================================
-- 5. DUPLICATE PATIENT DETECTION & MERGING TABLES
-- =============================================================================

-- Table: duplicates_duplicateflag
-- System-detected or staff-flagged potential duplicate patient profiles
CREATE TABLE IF NOT EXISTS public.duplicates_duplicateflag (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_a_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    patient_b_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    match_score numeric(5, 2) NOT NULL CHECK (match_score >= 0 AND match_score <= 100),
    matched_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    status varchar(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'dismissed', 'merged')),
    flagged_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at timestamp with time zone NULL,
    flagged_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    reviewed_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT unique_duplicate_pair UNIQUE (patient_a_id, patient_b_id)
);
COMMENT ON TABLE public.duplicates_duplicateflag IS 'Algorithmic matching flags for potential duplicate patient records.';

-- Table: duplicates_mergelog
-- Detailed record of merged patient profiles with reversible conflict resolutions
CREATE TABLE IF NOT EXISTS public.duplicates_mergelog (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    merged_patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    field_resolutions jsonb NOT NULL DEFAULT '{}'::jsonb,
    merged_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversible_until timestamp with time zone NOT NULL,
    reversed boolean NOT NULL DEFAULT FALSE,
    merged_by_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE PROTECT DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.duplicates_mergelog IS 'Audit log of merged patient records with field resolutions and rollback window.';


-- =============================================================================
-- 6. DENTAL CHARTING & PROCEDURES TABLES
-- =============================================================================

-- Table: dental_chart_toothrecord
-- Per-tooth diagnosis and procedure status (FDI Tooth Notation 11-48, Primary 51-85)
CREATE TABLE IF NOT EXISTS public.dental_chart_toothrecord (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dentition_type varchar(10) NOT NULL DEFAULT 'adult' CHECK (dentition_type IN ('adult', 'primary')),
    tooth_number varchar(5) NOT NULL,
    surface varchar(10) NOT NULL DEFAULT 'whole' CHECK (surface IN ('mesial', 'distal', 'occlusal', 'buccal', 'lingual', 'incisal', 'whole')),
    condition varchar(20) NOT NULL CHECK (condition IN ('decay', 'filling', 'crown', 'bridge', 'implant', 'rct', 'missing', 'impacted', 'unerupted', 'supernumerary', 'fracture', 'mobility', 'sensitivity', 'healthy')),
    status varchar(10) NOT NULL DEFAULT 'existing' CHECK (status IN ('existing', 'planned', 'completed', 'rejected')),
    notes text NOT NULL DEFAULT '',
    recorded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    patient_id bigint NOT NULL REFERENCES public.patients_patient(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    recorded_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.dental_chart_toothrecord IS 'Individual tooth diagnosis, tooth surface, condition, and treatment status.';
COMMENT ON COLUMN public.dental_chart_toothrecord.tooth_number IS 'FDI 2-digit tooth numbering system (e.g. 11, 21, 36, 48)';

-- Table: dental_chart_endodonticdetail
-- Root canal treatment details for specific tooth records
CREATE TABLE IF NOT EXISTS public.dental_chart_endodonticdetail (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    working_length_mm numeric(4, 1) NULL,
    canal_count smallint NULL CHECK (canal_count >= 0),
    obturation_date date NULL,
    technique_notes text NOT NULL DEFAULT '',
    tooth_record_id bigint NOT NULL UNIQUE REFERENCES public.dental_chart_toothrecord(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.dental_chart_endodonticdetail IS 'Specialized root canal treatment measurements and obturation notes.';

-- Table: dental_chart_implantdetail
-- Dental implant tracking, specifications, batch/serial numbers, and warranty
CREATE TABLE IF NOT EXISTS public.dental_chart_implantdetail (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand varchar(100) NOT NULL DEFAULT '',
    diameter_mm numeric(4, 2) NULL,
    length_mm numeric(4, 2) NULL,
    batch_number varchar(100) NOT NULL DEFAULT '',
    serial_number varchar(100) NOT NULL DEFAULT '',
    placement_date date NULL,
    bone_graft_material varchar(150) NOT NULL DEFAULT '',
    expiry_date date NULL,
    warranty_months smallint NULL CHECK (warranty_months >= 0),
    tooth_record_id bigint NOT NULL UNIQUE REFERENCES public.dental_chart_toothrecord(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.dental_chart_implantdetail IS 'Dental implant metadata, serial numbers, dimensions, and warranty tracking.';

-- Table: dental_chart_orthodonticdetail
-- Orthodontic appliances, bracket specifications, and wire adjustment notes
CREATE TABLE IF NOT EXISTS public.dental_chart_orthodonticdetail (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appliance_type varchar(100) NOT NULL DEFAULT '',
    bracket_type varchar(100) NOT NULL DEFAULT '',
    wire_size varchar(50) NOT NULL DEFAULT '',
    position_notes text NOT NULL DEFAULT '',
    adjustment_date date NULL,
    tooth_record_id bigint NOT NULL UNIQUE REFERENCES public.dental_chart_toothrecord(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.dental_chart_orthodonticdetail IS 'Orthodontic treatment specifications, bracket details, and archwire changes.';

-- Table: dental_chart_toothrecordhistory
-- Detailed change log history for tooth record fields
CREATE TABLE IF NOT EXISTS public.dental_chart_toothrecordhistory (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_field varchar(50) NOT NULL,
    old_value varchar(255) NOT NULL DEFAULT '',
    new_value varchar(255) NOT NULL DEFAULT '',
    changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by_id bigint NULL REFERENCES public.accounts_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    tooth_record_id bigint NOT NULL REFERENCES public.dental_chart_toothrecord(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
COMMENT ON TABLE public.dental_chart_toothrecordhistory IS 'Audit timeline of edits made to individual tooth chart records.';


-- =============================================================================
-- 7. SESSION & ADMIN AUDIT TABLES
-- =============================================================================

-- Table: django_session
-- Active web application sessions
CREATE TABLE IF NOT EXISTS public.django_session (
    session_key varchar(40) NOT NULL PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS django_session_expire_date_idx ON public.django_session (expire_date);

-- Table: django_admin_log
-- Django built-in admin action log
CREATE TABLE IF NOT EXISTS public.django_admin_log (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_time timestamp with time zone NOT NULL,
    object_id text NULL,
    object_repr varchar(200) NOT NULL,
    action_flag smallint NOT NULL CHECK (action_flag >= 0),
    change_message text NOT NULL,
    content_type_id integer NULL REFERENCES public.django_content_type(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    user_id bigint NOT NULL REFERENCES public.accounts_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);


-- =============================================================================
-- 8. INDEXES FOR PERFORMANCE OPTIMIZATION
-- =============================================================================

CREATE INDEX IF NOT EXISTS accounts_user_username_like ON public.accounts_user (username varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS accounts_loginhistory_user_id ON public.accounts_loginhistory (user_id);
CREATE INDEX IF NOT EXISTS accounts_otpverification_user_id ON public.accounts_otpverification (user_id);
CREATE INDEX IF NOT EXISTS accounts_auditlog_user_id ON public.accounts_auditlog (user_id);

CREATE INDEX IF NOT EXISTS patients_patient_patient_code_like ON public.patients_patient (patient_code varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS patients_patient_phone ON public.patients_patient (phone);
CREATE INDEX IF NOT EXISTS patients_patient_registered_by_id ON public.patients_patient (registered_by_id);
CREATE INDEX IF NOT EXISTS patients_patient_merged_into_id ON public.patients_patient (merged_into_id);
CREATE INDEX IF NOT EXISTS patients_guardian_patient_id ON public.patients_guardian (patient_id);
CREATE INDEX IF NOT EXISTS patients_medicalhistory_patient_id ON public.patients_medicalhistory (patient_id);
CREATE INDEX IF NOT EXISTS patients_allergy_patient_id ON public.patients_allergy (patient_id);
CREATE INDEX IF NOT EXISTS patients_familylink_patient_id ON public.patients_familylink (patient_id);
CREATE INDEX IF NOT EXISTS patients_familylink_related_patient_id ON public.patients_familylink (related_patient_id);

CREATE INDEX IF NOT EXISTS vitals_vitals_patient_id ON public.vitals_vitals (patient_id);
CREATE INDEX IF NOT EXISTS vitals_vitals_recorded_at ON public.vitals_vitals (recorded_at);

CREATE INDEX IF NOT EXISTS duplicates_duplicateflag_patient_a_id ON public.duplicates_duplicateflag (patient_a_id);
CREATE INDEX IF NOT EXISTS duplicates_duplicateflag_patient_b_id ON public.duplicates_duplicateflag (patient_b_id);
CREATE INDEX IF NOT EXISTS duplicates_mergelog_primary_patient_id ON public.duplicates_mergelog (primary_patient_id);
CREATE INDEX IF NOT EXISTS duplicates_mergelog_merged_patient_id ON public.duplicates_mergelog (merged_patient_id);

CREATE INDEX IF NOT EXISTS dental_chart_toothrecord_patient_id ON public.dental_chart_toothrecord (patient_id);
CREATE INDEX IF NOT EXISTS dental_chart_toothrecord_tooth_number ON public.dental_chart_toothrecord (tooth_number);
CREATE INDEX IF NOT EXISTS dental_chart_toothrecordhistory_tooth_record_id ON public.dental_chart_toothrecordhistory (tooth_record_id);

COMMIT;
