# Generated by Django 6.0.7 on 2026-08-06 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('registration', 'Registration'), ('pre_treatment', 'Pre-Treatment'), ('intra_procedure', 'During Procedure'), ('post_treatment', 'Post-Treatment')], max_length=20)),
                ('bp_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_sugar', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False, editable=False)),
                ('flagged_reason', models.CharField(blank=True, editable=False, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
