# Generated by Django 6.0.7 on 2026-07-29 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_resolutions', models.JSONField(default=dict)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('reversible_until', models.DateTimeField()),
                ('reversed', models.BooleanField(default=False)),
                ('merged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_performed', to=settings.AUTH_USER_MODEL)),
                ('merged_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_as_absorbed', to='patients.patient')),
                ('primary_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_as_primary', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_fields', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('merged', 'Merged')], default='pending', max_length=10)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates_flagged', to=settings.AUTH_USER_MODEL)),
                ('patient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_a', to='patients.patient')),
                ('patient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_b', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient_a', 'patient_b'), name='unique_duplicate_pair')],
            },
        ),
    ]
