# Generated by Django 6.0.7 on 2026-08-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerioExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('diagnosis_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perio_exams', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerioToothMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(max_length=5)),
                ('mobility_grade', models.PositiveSmallIntegerField(default=0)),
                ('furcation_grade', models.PositiveSmallIntegerField(default=0)),
                ('plaque_present', models.BooleanField(default=False)),
                ('calculus_present', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_measurements', to='perio_chart.perioexam')),
            ],
        ),
        migrations.CreateModel(
            name='PerioSiteReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('mesiobuccal', 'Mesiobuccal'), ('buccal', 'Buccal'), ('distobuccal', 'Distobuccal'), ('mesiolingual', 'Mesiolingual'), ('lingual', 'Lingual'), ('distolingual', 'Distolingual')], max_length=15)),
                ('pocket_depth_mm', models.PositiveSmallIntegerField()),
                ('recession_mm', models.SmallIntegerField(default=0)),
                ('bleeding_on_probing', models.BooleanField(default=False)),
                ('suppuration', models.BooleanField(default=False)),
                ('tooth_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_readings', to='perio_chart.periotoothmeasurement')),
            ],
        ),
    ]
