# Generated by Django 6.0.7 on 2026-08-21 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chief_complaint', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed to Patient'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_approved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consent_required', models.BooleanField(default=True)),
                ('consent_signed', models.BooleanField(default=False)),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_signature', models.TextField(blank=True)),
                ('ai_generated_explanation', models.TextField(blank=True)),
                ('revision_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans_assigned', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(blank=True, max_length=5)),
                ('surface', models.CharField(blank=True, max_length=10)),
                ('procedure_name', models.CharField(max_length=150)),
                ('phase', models.CharField(choices=[('urgent', 'Urgent'), ('preventive', 'Preventive'), ('restorative', 'Restorative'), ('cosmetic', 'Cosmetic')], default='restorative', max_length=15)),
                ('visit_sequence', models.PositiveSmallIntegerField(default=1)),
                ('expected_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='treatment_plans.treatmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlanRevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField()),
                ('reason_for_change', models.TextField()),
                ('snapshot', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_logs', to='treatment_plans.treatmentplan')),
            ],
        ),
    ]
